# Generated by Django 4.1.7 on 2023-03-14 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscribepage",
            name="subject",
            field=models.CharField(
                blank=True,
                help_text="Subject of the email that will be sent to new registrants",
                max_length=255,
            ),
        ),
    ]
