# Generated by Django 4.1.7 on 2023-03-14 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0002_alter_subscribepage_subject"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscribepage",
            name="admin_address",
        ),
        migrations.AlterField(
            model_name="subscribepage",
            name="subject",
            field=models.CharField(blank=True, max_length=255, verbose_name="subject"),
        ),
    ]
