# Generated by Django 4.1.7 on 2023-03-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0003_remove_subscribepage_admin_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscribepage",
            name="auto_register_to_mailchimp",
            field=models.BooleanField(default=True),
        ),
    ]
