# Generated by Django 4.1.7 on 2023-03-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0002_volunteerexperience_professionalexperience"),
    ]

    operations = [
        migrations.AlterField(
            model_name="professionalexperience",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="volunteerexperience",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
