# Generated by Django 4.1.7 on 2023-03-06 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("about", "0003_alter_professionalexperience_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="professionalexperience",
            name="location",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="professionalexperience",
            name="org_logo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="work_org_logo",
                to="wagtailimages.image",
            ),
        ),
    ]
