# Generated by Django 4.1.7 on 2023-03-07 21:41

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.contrib.table_block.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailvideos", "0013_add_choose_permissions"),
        ("portfolio", "0002_codingportfoliopage_creativeportfoliopage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="animation",
            name="demo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="animation_demo",
                to="wagtailvideos.video",
            ),
        ),
        migrations.AddField(
            model_name="animation",
            name="description",
            field=wagtail.fields.StreamField(
                [
                    ("heading", wagtail.blocks.CharBlock(form_classname="title")),
                    ("paragraph", wagtail.blocks.RichTextBlock()),
                    ("image", wagtail.images.blocks.ImageChooserBlock()),
                    ("table", wagtail.contrib.table_block.blocks.TableBlock()),
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
        migrations.AddField(
            model_name="animation",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
