# Generated by Django 4.1.7 on 2023-03-07 23:29

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("wagtaildocs", "0012_uploadeddocument"),
        ("portfolio", "0003_animation_demo_animation_description_animation_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="animation",
            name="raw_file",
        ),
        migrations.CreateModel(
            name="RawFiles",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "animation",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raw_files",
                        to="portfolio.animation",
                    ),
                ),
                (
                    "raw_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtaildocs.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Raw File",
                "verbose_name_plural": "Raw Files",
            },
        ),
    ]
