# Generated by Django 4.1.7 on 2023-03-08 00:18

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("portfolio", "0005_creativeportfoliopage_body"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhotoArt",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="photo_art",
                        to="portfolio.creativeportfoliopage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Photo Art",
                "verbose_name_plural": "Photo Art",
            },
        ),
    ]
