# Generated by Django 4.1.7 on 2023-03-08 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("portfolio", "0007_alter_photoart_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photoart",
            name="image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
