# Generated by Django 4.1.7 on 2023-03-08 15:43

from django.db import migrations
import wagtail.blocks
import wagtail.contrib.table_block.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resourcespage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", wagtail.blocks.CharBlock(form_classname="title")),
                    ("paragraph", wagtail.blocks.RichTextBlock()),
                    ("image", wagtail.images.blocks.ImageChooserBlock()),
                    ("table", wagtail.contrib.table_block.blocks.TableBlock()),
                    (
                        "podcast",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "description",
                                    wagtail.blocks.RichTextBlock(
                                        blank=True, form_classname="full", null=True
                                    ),
                                )
                            ]
                        ),
                    ),
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
        migrations.DeleteModel(
            name="Podcast",
        ),
    ]
